### ISSUE TITLE
Can't find entrypoint.sh trying to debug

### ISSUE THREAD

**Issue by kokokenada** [jshimko/meteor-launchpad#38] opened 2017-04-25 18:35 UTC
When I build my container based on jshimko/meteor-launchpad:latest , I'm getting out of memory errors. (https://github.com/meteor/meteor/issues/8157) . (Only fails in the Docker build, it is fine otherwise).  To find a workaround, I'm trying to debug my partially built container with:
````
docker run -t - i <image> --entrypoint /bin/sh
````
but I keep getting:
````
docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"./entrypoint.sh\": stat ./entrypoint.sh: no such file or directory".
````

**Comment by jshimko** [comment] 2017-04-25 18:41
I suspect this is either that you don't have enough memory or it's just a general Docker usage error.  Nobody else is reporting this problem (including me - and I've done about 10 builds today), so can you please provide reproduction steps that reliably cause this?

**Comment by jshimko** [comment] 2017-04-25 18:41
A reproduction repo would be ideal.  Something I can just clone and build.

**Comment by kokokenada** [comment] 2017-04-25 19:43
Sure.  This is the repo: https://github.com/kokokenada/for-real-cards

**Comment by jshimko** [comment] 2017-04-26 14:39
This is because you can't build the mobile versions inside the container.  You're not finding `entrypoint.sh` because the build isn't actually finishing.

Removing `ios` and `android` from your `.meteor/platforms` file fixes this.

**Comment by kokokenada** [comment] 2017-04-26 16:32
The pull request https://github.com/jshimko/meteor-launchpad/pull/37 changes the build script to use the --server-only flag so you don't have to manually remove the platforms before you build.  Once that mobile platform problem is resolved, then I run into the problem described here: https://github.com/meteor/meteor/issues/8157 .  This issue is about the fact that I am unable to trouble shoot the problem by running a shell because it can't find the entry point script.  So, I'm unable to easily try the various work arounds discussed in 8157. I'm wondering if there was a way to construct meteor-launchpad to permit debugging.

**Comment by jshimko** [comment] 2017-04-26 16:42
See my notes in your PR.  None of your changes can be merged without breaking this project for everyone else, so that's definitely not going to be an adequate solution.

As I mentioned above about the entrypoint script, that's because your build failed.  You're trying to debug a container that never finished building.  That's not a debug limitation of `meteor-launchpad`.  Debugging a successful build would work as expected.

Aside from that, your repo builds fine for me when I remove `ios` and `android` platforms, so I suspect you just don't have enough memory on your build machine (or something like that).

**Comment by kokokenada** [comment] 2017-04-27 19:33
Are we talking about the same PR?  There are no comments on the one I'm referring to: https://github.com/jshimko/meteor-launchpad/pull/37   How would adding --server-only to the build break it for everyone else?

I was able to make the build finish by removing the minifier plugin. A lot of other people are having problems in different environments. (I have a 16GB Mac and Docker was configured with 12GB). (https://github.com/meteor/meteor/issues/8157) 

Re not finding the entry point, I'm new to docker, but the advice I was reading for debugging is to shell into the container.  This doesn't work if meteor launch doesn't finish.  Perhaps this could be improved.

**Closed as completed** 2017-07-28 04:08 UTC
