### ISSUE TITLE
Keep on getting this error when building within CI pipeline from gitlab and on mac os as well

### ISSUE THREAD

**Issue by virtuman** [jshimko/meteor-launchpad#7] opened 2016-10-26 00:47 UTC
any idea what i'm doing wrong?

**FROM GITLAB-RUNNER HOST**

```
Purging configuration files for wget (1.16-1+deb8u1) ...

Step 1 : RUN bash $BUILD_SCRIPTS_DIR/install-mongo.sh
 ---> Running in b83ec9573d9d
current mongo setting is INSTALL_MONGO = false
Step 1 : RUN cd $APP_SOURCE_DIR &&             bash $BUILD_SCRIPTS_DIR/install-meteor.sh &&             bash $BUILD_SCRIPTS_DIR/build-meteor.sh &&             bash $BUILD_SCRIPTS_DIR/post-build-cleanup.sh
 ---> Running in b0d163991c45
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  7784    0  7784    0     0  15385      0 --:--:-- --:--:-- --:--:-- 15383
sed: -e expression #1, char 29: unterminated `s' command
The command '/bin/sh -c cd $APP_SOURCE_DIR &&             bash $BUILD_SCRIPTS_DIR/install-meteor.sh &&             bash $BUILD_SCRIPTS_DIR/build-meteor.sh &&             bash $BUILD_SCRIPTS_DIR/post-build-cleanup.sh' returned a non-zero code: 1
ERROR: Build failed: exit code 1
```

**FROM MAC OS**

```
 ---> Running in 608aaa13397f
current mongo setting is INSTALL_MONGO = false
Step 1 : RUN cd $APP_SOURCE_DIR &&             bash $BUILD_SCRIPTS_DIR/install-meteor.sh &&             bash $BUILD_SCRIPTS_DIR/build-meteor.sh &&             bash $BUILD_SCRIPTS_DIR/post-build-cleanup.sh
 ---> Running in 7afab25ff5a2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7784    0  7784    0     0  15985      0 --:--:-- --:--:-- --:--:-- 16016
sed: -e expression #1, char 29: unterminated `s' command
The command '/bin/sh -c cd $APP_SOURCE_DIR &&             bash $BUILD_SCRIPTS_DIR/install-meteor.sh &&             bash $BUILD_SCRIPTS_DIR/build-meteor.sh &&             bash $BUILD_SCRIPTS_DIR/post-build-cleanup.sh' returned a non-zero code: 1

```

**Comment by jshimko** [comment] 2016-10-26 01:42
Have you customized something?  I see things in those logs that are not part of this project.  Like...

```
current mongo setting is INSTALL_MONGO = false
```

or...

```
sed: -e expression #1, char 29: unterminated `s' command
```

Neither of those are coming from this base image.

**Comment by jshimko** [comment] 2016-10-26 05:18
Oops, sorry.  It looks like that first line is actually in the image.  That was a leftover debug line from when I was working on the Mongo stuff.  Just removed it.

The only place that `sed` command is used is when [detecting the version of Meteor that your app is using](https://github.com/jshimko/meteor-launchpad/blob/master/scripts/install-meteor.sh#L15).  I haven't ever seen that issue though.  Are you definitely running this from a Meteor project?

If you can publish an example that reproduces your issue, I'd be happy to take a look at it.

**Comment by jshimko** [comment] 2016-10-27 18:34
I think I may have figured this out.  Try pulling the latest image and see if it works for you now.

**Comment by jshimko** [comment] 2016-10-31 20:32
I was able to reproduce the issue and have since fixed it, so I'm going to close this for now.  Feel free to reopen it if you run into the problem with the latest build.

**Closed as completed by jshimko** 2016-10-31 20:32 UTC
