### ISSUE TITLE
Build error when add-platform

### ISSUE THREAD

**Issue by shar0** [jshimko/meteor-launchpad#57] opened 2017-08-16 12:08 UTC
If add iOS/Android platform, docker image will failed to build

> Supply the server hostname and port in the --server option for mobile app builds.

Remove iOS/Android platform could fix this.

Does here has any way to keep it both?

**Comment by jshimko** [comment] 2017-08-16 14:10
This has been fixed in `v2.1.1`.  Please give it a test and let me know.

**Comment by jshimko** [comment] 2017-08-16 15:39
Closing this as it's a duplicate of #54.  Feel free to comment there if you continue to have this issue with v2.1.1 or later.

**Closed as completed by jshimko** 2017-08-16 15:39 UTC
